'use client'

import { useState } from 'react'
import { doc, setDoc, serverTimestamp } from 'firebase/firestore'
import { MapPin, Sprout } from 'lucide-react'
import { firebaseDb } from '@/lib/firebase'

export type FarmerProfile = { name: string; farm: string; state: string; crop: string; hectares: string }
export function FarmerProfileSetup({ uid, initialName, onDone }: { uid: string; initialName?: string | null; onDone: (profile: FarmerProfile) => void }) {
  const [profile,setProfile] = useState<FarmerProfile>({ name: initialName || '', farm: '', state: 'Maharashtra', crop: 'Tomato', hectares: '' }); const [saving,setSaving] = useState(false); const [error,setError] = useState('')
  const change = (key:keyof FarmerProfile) => (e:React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setProfile(p=>({...p,[key]:e.target.value}))
  const submit = async (e:React.FormEvent) => { e.preventDefault(); if (!profile.name || !profile.farm || !profile.hectares) { setError('Add your name, farm name, and land size to continue.'); return } setSaving(true); try { if (firebaseDb) await setDoc(doc(firebaseDb,'farmerProfiles',uid), {...profile, ownerId:uid, updatedAt:serverTimestamp()}, {merge:true}); else localStorage.setItem(`agrivision-profile-${uid}`,JSON.stringify(profile)); onDone(profile) } catch { setError('Could not save to Firestore. Check your Firebase database rules, then try again.') } finally { setSaving(false) } }
  return <main className="min-h-screen bg-[#08150e] px-5 py-10 text-[#eef5e4]"><form onSubmit={submit} className="mx-auto max-w-2xl animate-reveal rounded-[32px] border border-white/10 bg-[#112019] p-6 shadow-2xl md:p-10"><div className="flex items-center gap-3 text-[#d5ff4d]"><div className="grid size-11 place-items-center rounded-2xl bg-[#d5ff4d] text-[#102016]"><Sprout/></div><span className="font-mono text-[10px] tracking-[.24em]">CREATE FARMER PROFILE</span></div><h1 className="mt-6 text-4xl font-semibold tracking-[-.04em]">Let’s make this farm yours.</h1><p className="mt-3 text-sm leading-6 text-white/50">This creates a separate profile under your account. Your future scans, field markers, and treatments belong only to this farmer ID.</p><div className="mt-8 grid gap-4 md:grid-cols-2"><Field label="Farmer name"><input value={profile.name} onChange={change('name')} placeholder="Om Rane"/></Field><Field label="Farm name"><input value={profile.farm} onChange={change('farm')} placeholder="Green Valley Farm"/></Field><Field label="State"><select value={profile.state} onChange={change('state')}>{['Maharashtra','Gujarat','Karnataka','Tamil Nadu','Madhya Pradesh','Uttar Pradesh'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Primary crop"><select value={profile.crop} onChange={change('crop')}>{['Tomato','Wheat','Cotton','Grapes','Rice','Potato'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Land size"><input value={profile.hectares} onChange={change('hectares')} placeholder="e.g. 4.5 hectares"/></Field><div className="rounded-xl border border-[#d5ff4d]/20 bg-[#d5ff4d]/[.06] p-4 text-xs leading-5 text-white/55"><MapPin size={15} className="mb-2 text-[#d5ff4d]"/>You can add precise field pins from the India map after setup.</div></div>{error && <p className="mt-4 text-sm text-[#ef8354]">{error}</p>}<button disabled={saving} className="mt-8 w-full rounded-xl bg-[#d5ff4d] py-3.5 text-sm font-semibold text-[#102016] disabled:opacity-60">{saving ? 'Saving your farm…' : 'Create my farmer profile'}</button></form></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block text-xs text-white/45"><span>{label}</span><div className="mt-2 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-white/10 [&_input]:bg-black/20 [&_input]:px-4 [&_input]:py-3 [&_input]:text-sm [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-white/10 [&_select]:bg-black/20 [&_select]:px-4 [&_select]:py-3 [&_select]:text-sm">{children}</div></label> }
