'use client'

import { Cloud, ContactShadows, Float, Html, Line, OrbitControls, Sky, Stars } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'
import { useMemo, useRef, useState } from 'react'
import * as THREE from 'three'

type Mode = 'sensor' | 'planner'
function Ground({ mode }: { mode: Mode }) { const rows = mode === 'sensor' ? 10 : 7; return <group rotation-x={-Math.PI / 2}><mesh position={[0,0,-.2]}><planeGeometry args={[13,10]} /><meshStandardMaterial color="#aabf7e" roughness={1} /></mesh>{Array.from({length:rows}).map((_,i)=><group key={i} position={[0,i*.75-3,0]}><mesh><boxGeometry args={[10,.42,.1]} /><meshStandardMaterial color={i%2?'#608f48':'#75a555'} roughness={1}/></mesh>{Array.from({length: 16}).map((_,j)=><mesh key={j} position={[j*.6-4.5,.18,.1]} rotation-z={(j%2?-.08:.08)}><coneGeometry args={[.12,.42,5]} /><meshStandardMaterial color={i%3?'#356d3f':'#527f42'} /></mesh>)}</group>)}{mode==='planner'&&Array.from({length:4}).map((_,i)=><mesh key={i} position={[-3+i*2, .01, 3.8]}><boxGeometry args={[1.6,.04,.25]}/><meshStandardMaterial color="#d5ff4d" emissive="#d5ff4d" emissiveIntensity={.35}/></mesh>)}</group> }
function Platform() { return <group position={[0,2.2,0]}><mesh><boxGeometry args={[4.6,.18,2.5]}/><meshStandardMaterial color="#dcc995" roughness={.65}/></mesh><mesh position={[0,-.18,0]}><boxGeometry args={[4.4,.08,2.3]}/><meshStandardMaterial color="#5d704c"/></mesh><Solar x={-1.3}/><Solar x={1.25}/><Label text="STATUS PLATFORM" position={[0,.25,0]} /></group> }
function Solar({x}:{x:number}) { return <group position={[x, .15, -.35]} rotation-x={-.2}><mesh><boxGeometry args={[1.1,.05,.62]}/><meshStandardMaterial color="#183b55" metalness={.5}/></mesh>{[-.35,0,.35].map((z)=><mesh key={z} position={[0,.04,z]}><boxGeometry args={[1.04,.02,.015]}/><meshStandardMaterial color="#d5ff4d"/></mesh>)}</group> }
function Mast() { return <group position={[0,3.45,0]}><mesh><cylinderGeometry args={[.05,.05,2.5,10]}/><meshStandardMaterial color="#273d2d"/></mesh><WindVane position={[0,1.15,0]}/><Anemometer position={[0,1.45,0]}/></group> }
function WindVane({position}:{position:[number,number,number]}) { return <group position={position}><mesh rotation-z={Math.PI/2}><boxGeometry args={[.9,.05,.06]}/><meshStandardMaterial color="#ef8354"/></mesh><mesh position={[.45,0,0]} rotation-z={Math.PI/2}><coneGeometry args={[.12,.35,4]}/><meshStandardMaterial color="#ef8354"/></mesh></group> }
function Anemometer({position}:{position:[number,number,number]}) { const ref=useRef<THREE.Group>(null); useFrame(({clock})=>{if(ref.current)ref.current.rotation.y=clock.elapsedTime*3}); return <group ref={ref} position={position}>{[0,Math.PI/2,Math.PI,Math.PI*1.5].map((r)=><mesh key={r} rotation-y={r} position={[Math.sin(r)*.32,0,Math.cos(r)*.32]}><sphereGeometry args={[.1,12,12]}/><meshStandardMaterial color="#f1f4e7"/></mesh>)}</group> }
function SoilProbe({position,label,color}:{position:[number,number,number];label:string;color:string}) { const [selected,setSelected]=useState(false); return <group position={position} onClick={()=>setSelected(!selected)}><mesh><cylinderGeometry args={[.08,.08,.9,12]}/><meshStandardMaterial color="#17261a"/></mesh><mesh position={[0,.5,0]}><sphereGeometry args={[.17,18,18]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={1.6}/></mesh><Line points={[[0,.6,0],[position[0]*-0.9,1.6,position[2]*-0.7]]} color={color} transparent opacity={.25}/><Label text={selected ? `${label} · selected` : label} position={[.25,.65,0]} /></group> }
function Drone() { const ref=useRef<THREE.Group>(null); useFrame(({clock})=>{if(ref.current){ref.current.position.x=Math.sin(clock.elapsedTime*.35)*2;ref.current.position.z=Math.cos(clock.elapsedTime*.35)*1.4;ref.current.rotation.y=clock.elapsedTime*.2}}); return <group ref={ref} position={[0,5.6,0]}><mesh><boxGeometry args={[.62,.14,.36]}/><meshStandardMaterial color="#f1f4e7"/></mesh>{[-1,1].flatMap(x=>[-1,1].map(z=><group key={`${x}-${z}`} position={[x*.45,0,z*.25]}><mesh><cylinderGeometry args={[.035,.035,.55,8]}/><meshStandardMaterial color="#1b3021"/></mesh><mesh rotation-z={Math.PI/2}><boxGeometry args={[.48,.025,.05]}/><meshStandardMaterial color="#d5ff4d"/></mesh></group>))}<Label text="SCOUT DRONE · LIVE" position={[0,.4,0]} /></group> }
function Barn() { return <group position={[4,1,-3]}><mesh><boxGeometry args={[1.7,1.1,1.2]}/><meshStandardMaterial color="#c57c58"/></mesh><mesh position={[0,.8,0]} rotation-z={Math.PI/4}><coneGeometry args={[1.3,.9,4]}/><meshStandardMaterial color="#714c39"/></mesh></group> }
function Greenhouse() { return <group position={[-4,.55,-3.1]} rotation-y={.28}><mesh><boxGeometry args={[2.5,1.1,1.4]}/><meshPhysicalMaterial color="#bdefff" transparent opacity={.42} roughness={.15} metalness={.15}/></mesh>{[-.9,0,.9].map(x => <mesh key={x} position={[x,0,0]}><boxGeometry args={[.06,1.15,1.47]}/><meshStandardMaterial color="#e8f4df"/></mesh>)}<Label text="SMART GREENHOUSE" position={[0,1,0]} /></group> }
function Tree({position}:{position:[number,number,number]}) { return <group position={position}><mesh position={[0,.55,0]}><cylinderGeometry args={[.12,.18,1.1,8]}/><meshStandardMaterial color="#71553a"/></mesh><mesh position={[0,1.25,0]}><sphereGeometry args={[.65,12,12]}/><meshStandardMaterial color="#2d713c" roughness={.9}/></mesh><mesh position={[.34,1.45,.12]}><sphereGeometry args={[.42,12,12]}/><meshStandardMaterial color="#4e9347" roughness={.9}/></mesh></group> }
function Irrigation() { return <group position={[0,.1,2.8]}>{Array.from({length:6}).map((_,i)=><mesh key={i} position={[i*1.5-3.75,0,0]}><cylinderGeometry args={[.08,.08,.18,12]}/><meshStandardMaterial color="#283b40" metalness={.55}/></mesh>)}<mesh rotation-z={Math.PI/2}><cylinderGeometry args={[.035,.035,9,10]}/><meshStandardMaterial color="#408bc4" emissive="#166595" emissiveIntensity={.35}/></mesh><Label text="AUTONOMOUS IRRIGATION" position={[0,.35,0]} /></group> }
function Label({text,position}:{text:string;position:[number,number,number]}) { return <Html distanceFactor={8} position={position}><div className="pointer-events-none whitespace-nowrap rounded-full border border-[#d5ff4d]/45 bg-[#102016]/90 px-2 py-1 font-mono text-[8px] uppercase tracking-[.12em] text-[#e9ffb2] shadow-lg">{text}</div></Html> }
export function FarmScene({ mode='sensor' }: { mode?: Mode }) { return <div className="h-full min-h-[420px] w-full overflow-hidden rounded-[26px] bg-[#b8c990]"><Canvas shadows camera={{position:[8,6.2,9],fov:36}} dpr={[1,2]}><color attach="background" args={['#b8c990']}/><ambientLight intensity={1.35}/><directionalLight castShadow position={[5,9,4]} intensity={3.2} color="#fff1c2" shadow-mapSize={[2048,2048]}/><Sky sunPosition={[5,4,2]} turbidity={7} rayleigh={1.5}/><Cloud position={[-5,7,-5]} opacity={.28} speed={.18} segments={18}/><Stars radius={35} depth={20} count={450} factor={2} saturation={0}/><Ground mode={mode}/><Irrigation/>{[-5,5].flatMap(x=>[-3,0,3].map(z=><Tree key={`${x}${z}`} position={[x,.1,z]}/>))}{mode==='sensor'?<><Float floatIntensity={.7} rotationIntensity={.12}><Platform/><Mast/></Float><SoilProbe position={[-3,.7,.6]} label="SOIL · 42%" color="#d5ff4d"/><SoilProbe position={[2.4,.7,-.8]} label="WIND · 12 KM/H" color="#f7c948"/><SoilProbe position={[0,.7,1.6]} label="NITROGEN · GOOD" color="#f1f4e7"/><SoilProbe position={[3,.7,1.5]} label="RAIN · 18%" color="#73c9ff"/><Drone/></>:<><Barn/><Greenhouse/><Label text="FIELD A · WHEAT" position={[-2,1,1]}/></>}<ContactShadows position={[0,.01,0]} opacity={.38} scale={18} blur={2.5} far={5}/><OrbitControls enablePan={false} minDistance={6} maxDistance={15} maxPolarAngle={Math.PI/2.02}/></Canvas></div> }
